# Dependencies
#markdown:         redcarpet
markdown:         kramdown
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            XOS Guide
tagline:          'XOS Guide'
description:      'A guide to using, developing, and<br> operating XOS'
url:              http://open-cloud.github.io
baseurl:          /

author:
  name:           'open-cloud'
  url:            https://github.com/open-cloud

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/open-cloud/open-cloud.github.io
